language: node_js

node_js:
  - "8"
  - "10"

script:
  - set -e
  - npm run test

stages:
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: browser-test
      script:
        - set -e
        - echo 1
        # - npm run test-karma

    - stage: deploy
      script: 
        - set -e
        - npm run test
        - npm run coveralls
        - export REMOTE_VERSION=$(npm dist-tag ls immutable-assign | cut -d' ' -f 2)
        - export LOCAL_VERSION=$(node -p -e "require('./package.json').version")
        - test "$REMOTE_VERSION" != "$LOCAL_VERSION" && npm publish || true

