language: node_js

node_js:
  - "8"
  - "10"

script:
  - set -e
  - npm run test

stages:
  - test
  - browser-test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: browser-test
      script: CUSTOM_JOB_INDEX=0 npm run test-karma
    - script: CUSTOM_JOB_INDEX=1 npm run test-karma
    - script: CUSTOM_JOB_INDEX=2 npm run test-karma
    - script: CUSTOM_JOB_INDEX=3 npm run test-karma
    - script: CUSTOM_JOB_INDEX=4 npm run test-karma
    - script: CUSTOM_JOB_INDEX=5 npm run test-karma
    - script: CUSTOM_JOB_INDEX=6 npm run test-karma
    - script: CUSTOM_JOB_INDEX=7 npm run test-karma
    - script: CUSTOM_JOB_INDEX=8 npm run test-karma
    - script: CUSTOM_JOB_INDEX=9 npm run test-karma
    - script: CUSTOM_JOB_INDEX=10 npm run test-karma
    - script: CUSTOM_JOB_INDEX=11 npm run test-karma
    - script: CUSTOM_JOB_INDEX=12 npm run test-karma
    - script: CUSTOM_JOB_INDEX=13 npm run test-karma

    - stage: deploy
      script: 
        - set -e
        - npm run test
        - npm run coveralls
        - export REMOTE_VERSION=$(npm dist-tag ls immutable-assign | cut -d' ' -f 2)
        - export LOCAL_VERSION=$(node -p -e "require('./package.json').version")
        - test "$REMOTE_VERSION" != "$LOCAL_VERSION" && npm publish || true

