language: node_js
node_js:
  # - "10"
  # - "9"
  - "8"
  # - "6"
  # - "4"
after_success: 
 - npm run coveralls
 - npm run test-karma
 - export REMOTE_VERSION=$(npm dist-tag ls immutable-assign | cut -d' ' -f 2)
 - export LOCAL_VERSION=$(node -p -e "require('./package.json').version")
 - test "$REMOTE_VERSION" != "$LOCAL_VERSION" && npm publish 
