language: node_js
node_js:
  # - "10"
  # - "9"
  - "8"
  # - "6"
  # - "4"

stages:
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - set -e
        - echo 1
        - echo 2 

    - stage: test2
      script: 
        - set -e
        - echo 3

    - stage: deploy
      script: 
        - set -e
        - echo 4

# script:
#   - set -e
#   - npm run test
#   - npm run coveralls
#   # - npm run test-karma
#   - export REMOTE_VERSION=$(npm dist-tag ls immutable-assign | cut -d' ' -f 2)
#   - export LOCAL_VERSION=$(node -p -e "require('./package.json').version")
#   - test "$REMOTE_VERSION" != "$LOCAL_VERSION" && npm publish || true
